// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer_message.proto

package proto_def;

public final class PeerMessage {
  private PeerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_def.Level)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 level = 1;</code>
     */
    int getLevel();

    /**
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();
  }
  /**
   * <pre>
   * 发送消息时需要保证level和title两个字段至少一个有值。
   * 收到消息时不能假定两个字段的值均存在，在不存在时需要去本地字典表中查询
   * </pre>
   *
   * Protobuf type {@code proto_def.Level}
   */
  public  static final class Level extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_def.Level)
      LevelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Level.newBuilder() to construct.
    private Level(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Level() {
      level_ = 0;
      title_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Level(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              level_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_def.PeerMessage.internal_static_proto_def_Level_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_def.PeerMessage.internal_static_proto_def_Level_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_def.PeerMessage.Level.class, proto_def.PeerMessage.Level.Builder.class);
    }

    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>int32 level = 1;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (level_ != 0) {
        output.writeInt32(1, level_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, level_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_def.PeerMessage.Level)) {
        return super.equals(obj);
      }
      proto_def.PeerMessage.Level other = (proto_def.PeerMessage.Level) obj;

      boolean result = true;
      result = result && (getLevel()
          == other.getLevel());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_def.PeerMessage.Level parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_def.PeerMessage.Level parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_def.PeerMessage.Level parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_def.PeerMessage.Level parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_def.PeerMessage.Level parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_def.PeerMessage.Level parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_def.PeerMessage.Level parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_def.PeerMessage.Level parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_def.PeerMessage.Level parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_def.PeerMessage.Level parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_def.PeerMessage.Level parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_def.PeerMessage.Level parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_def.PeerMessage.Level prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 发送消息时需要保证level和title两个字段至少一个有值。
     * 收到消息时不能假定两个字段的值均存在，在不存在时需要去本地字典表中查询
     * </pre>
     *
     * Protobuf type {@code proto_def.Level}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_def.Level)
        proto_def.PeerMessage.LevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_def.PeerMessage.internal_static_proto_def_Level_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_def.PeerMessage.internal_static_proto_def_Level_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_def.PeerMessage.Level.class, proto_def.PeerMessage.Level.Builder.class);
      }

      // Construct using proto_def.PeerMessage.Level.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        level_ = 0;

        title_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_def.PeerMessage.internal_static_proto_def_Level_descriptor;
      }

      @java.lang.Override
      public proto_def.PeerMessage.Level getDefaultInstanceForType() {
        return proto_def.PeerMessage.Level.getDefaultInstance();
      }

      @java.lang.Override
      public proto_def.PeerMessage.Level build() {
        proto_def.PeerMessage.Level result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto_def.PeerMessage.Level buildPartial() {
        proto_def.PeerMessage.Level result = new proto_def.PeerMessage.Level(this);
        result.level_ = level_;
        result.title_ = title_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_def.PeerMessage.Level) {
          return mergeFrom((proto_def.PeerMessage.Level)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_def.PeerMessage.Level other) {
        if (other == proto_def.PeerMessage.Level.getDefaultInstance()) return this;
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_def.PeerMessage.Level parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_def.PeerMessage.Level) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 1;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 1;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 1;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_def.Level)
    }

    // @@protoc_insertion_point(class_scope:proto_def.Level)
    private static final proto_def.PeerMessage.Level DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_def.PeerMessage.Level();
    }

    public static proto_def.PeerMessage.Level getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Level>
        PARSER = new com.google.protobuf.AbstractParser<Level>() {
      @java.lang.Override
      public Level parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Level(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Level> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Level> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto_def.PeerMessage.Level getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PeerUserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_def.PeerUserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string nickName = 2;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>string nickName = 2;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>string avatar = 3;</code>
     */
    java.lang.String getAvatar();
    /**
     * <code>string avatar = 3;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <code>.proto_def.Level vip = 4;</code>
     */
    boolean hasVip();
    /**
     * <code>.proto_def.Level vip = 4;</code>
     */
    proto_def.PeerMessage.Level getVip();
    /**
     * <code>.proto_def.Level vip = 4;</code>
     */
    proto_def.PeerMessage.LevelOrBuilder getVipOrBuilder();

    /**
     * <code>.proto_def.Level noble = 5;</code>
     */
    boolean hasNoble();
    /**
     * <code>.proto_def.Level noble = 5;</code>
     */
    proto_def.PeerMessage.Level getNoble();
    /**
     * <code>.proto_def.Level noble = 5;</code>
     */
    proto_def.PeerMessage.LevelOrBuilder getNobleOrBuilder();

    /**
     * <pre>
     *'F' for female, 'M' for male, 'U' for Unknown
     * </pre>
     *
     * <code>string gender = 6;</code>
     */
    java.lang.String getGender();
    /**
     * <pre>
     *'F' for female, 'M' for male, 'U' for Unknown
     * </pre>
     *
     * <code>string gender = 6;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();
  }
  /**
   * <pre>
   * 聊天室中消息/通知中用到的用户扩展信息
   * UI根据扩展信息中的用户等级和头衔决定欢迎通知和用户消息如何显示
   * </pre>
   *
   * Protobuf type {@code proto_def.PeerUserInfo}
   */
  public  static final class PeerUserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_def.PeerUserInfo)
      PeerUserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PeerUserInfo.newBuilder() to construct.
    private PeerUserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PeerUserInfo() {
      userId_ = "";
      nickName_ = "";
      avatar_ = "";
      gender_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PeerUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
            case 34: {
              proto_def.PeerMessage.Level.Builder subBuilder = null;
              if (vip_ != null) {
                subBuilder = vip_.toBuilder();
              }
              vip_ = input.readMessage(proto_def.PeerMessage.Level.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vip_);
                vip_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              proto_def.PeerMessage.Level.Builder subBuilder = null;
              if (noble_ != null) {
                subBuilder = noble_.toBuilder();
              }
              noble_ = input.readMessage(proto_def.PeerMessage.Level.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(noble_);
                noble_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_def.PeerMessage.internal_static_proto_def_PeerUserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_def.PeerMessage.internal_static_proto_def_PeerUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_def.PeerMessage.PeerUserInfo.class, proto_def.PeerMessage.PeerUserInfo.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nickName_;
    /**
     * <code>string nickName = 2;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    private volatile java.lang.Object avatar_;
    /**
     * <code>string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <code>string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIP_FIELD_NUMBER = 4;
    private proto_def.PeerMessage.Level vip_;
    /**
     * <code>.proto_def.Level vip = 4;</code>
     */
    public boolean hasVip() {
      return vip_ != null;
    }
    /**
     * <code>.proto_def.Level vip = 4;</code>
     */
    public proto_def.PeerMessage.Level getVip() {
      return vip_ == null ? proto_def.PeerMessage.Level.getDefaultInstance() : vip_;
    }
    /**
     * <code>.proto_def.Level vip = 4;</code>
     */
    public proto_def.PeerMessage.LevelOrBuilder getVipOrBuilder() {
      return getVip();
    }

    public static final int NOBLE_FIELD_NUMBER = 5;
    private proto_def.PeerMessage.Level noble_;
    /**
     * <code>.proto_def.Level noble = 5;</code>
     */
    public boolean hasNoble() {
      return noble_ != null;
    }
    /**
     * <code>.proto_def.Level noble = 5;</code>
     */
    public proto_def.PeerMessage.Level getNoble() {
      return noble_ == null ? proto_def.PeerMessage.Level.getDefaultInstance() : noble_;
    }
    /**
     * <code>.proto_def.Level noble = 5;</code>
     */
    public proto_def.PeerMessage.LevelOrBuilder getNobleOrBuilder() {
      return getNoble();
    }

    public static final int GENDER_FIELD_NUMBER = 6;
    private volatile java.lang.Object gender_;
    /**
     * <pre>
     *'F' for female, 'M' for male, 'U' for Unknown
     * </pre>
     *
     * <code>string gender = 6;</code>
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *'F' for female, 'M' for male, 'U' for Unknown
     * </pre>
     *
     * <code>string gender = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickName_);
      }
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
      }
      if (vip_ != null) {
        output.writeMessage(4, getVip());
      }
      if (noble_ != null) {
        output.writeMessage(5, getNoble());
      }
      if (!getGenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gender_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nickName_);
      }
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
      }
      if (vip_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getVip());
      }
      if (noble_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getNoble());
      }
      if (!getGenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_def.PeerMessage.PeerUserInfo)) {
        return super.equals(obj);
      }
      proto_def.PeerMessage.PeerUserInfo other = (proto_def.PeerMessage.PeerUserInfo) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getNickName()
          .equals(other.getNickName());
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && (hasVip() == other.hasVip());
      if (hasVip()) {
        result = result && getVip()
            .equals(other.getVip());
      }
      result = result && (hasNoble() == other.hasNoble());
      if (hasNoble()) {
        result = result && getNoble()
            .equals(other.getNoble());
      }
      result = result && getGender()
          .equals(other.getGender());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      if (hasVip()) {
        hash = (37 * hash) + VIP_FIELD_NUMBER;
        hash = (53 * hash) + getVip().hashCode();
      }
      if (hasNoble()) {
        hash = (37 * hash) + NOBLE_FIELD_NUMBER;
        hash = (53 * hash) + getNoble().hashCode();
      }
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_def.PeerMessage.PeerUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_def.PeerMessage.PeerUserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 聊天室中消息/通知中用到的用户扩展信息
     * UI根据扩展信息中的用户等级和头衔决定欢迎通知和用户消息如何显示
     * </pre>
     *
     * Protobuf type {@code proto_def.PeerUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_def.PeerUserInfo)
        proto_def.PeerMessage.PeerUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_def.PeerMessage.internal_static_proto_def_PeerUserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_def.PeerMessage.internal_static_proto_def_PeerUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_def.PeerMessage.PeerUserInfo.class, proto_def.PeerMessage.PeerUserInfo.Builder.class);
      }

      // Construct using proto_def.PeerMessage.PeerUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        nickName_ = "";

        avatar_ = "";

        if (vipBuilder_ == null) {
          vip_ = null;
        } else {
          vip_ = null;
          vipBuilder_ = null;
        }
        if (nobleBuilder_ == null) {
          noble_ = null;
        } else {
          noble_ = null;
          nobleBuilder_ = null;
        }
        gender_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_def.PeerMessage.internal_static_proto_def_PeerUserInfo_descriptor;
      }

      @java.lang.Override
      public proto_def.PeerMessage.PeerUserInfo getDefaultInstanceForType() {
        return proto_def.PeerMessage.PeerUserInfo.getDefaultInstance();
      }

      @java.lang.Override
      public proto_def.PeerMessage.PeerUserInfo build() {
        proto_def.PeerMessage.PeerUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto_def.PeerMessage.PeerUserInfo buildPartial() {
        proto_def.PeerMessage.PeerUserInfo result = new proto_def.PeerMessage.PeerUserInfo(this);
        result.userId_ = userId_;
        result.nickName_ = nickName_;
        result.avatar_ = avatar_;
        if (vipBuilder_ == null) {
          result.vip_ = vip_;
        } else {
          result.vip_ = vipBuilder_.build();
        }
        if (nobleBuilder_ == null) {
          result.noble_ = noble_;
        } else {
          result.noble_ = nobleBuilder_.build();
        }
        result.gender_ = gender_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_def.PeerMessage.PeerUserInfo) {
          return mergeFrom((proto_def.PeerMessage.PeerUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_def.PeerMessage.PeerUserInfo other) {
        if (other == proto_def.PeerMessage.PeerUserInfo.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        if (other.hasVip()) {
          mergeVip(other.getVip());
        }
        if (other.hasNoble()) {
          mergeNoble(other.getNoble());
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_def.PeerMessage.PeerUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_def.PeerMessage.PeerUserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <code>string nickName = 2;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 2;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 2;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 2;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <code>string avatar = 3;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }

      private proto_def.PeerMessage.Level vip_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto_def.PeerMessage.Level, proto_def.PeerMessage.Level.Builder, proto_def.PeerMessage.LevelOrBuilder> vipBuilder_;
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public boolean hasVip() {
        return vipBuilder_ != null || vip_ != null;
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public proto_def.PeerMessage.Level getVip() {
        if (vipBuilder_ == null) {
          return vip_ == null ? proto_def.PeerMessage.Level.getDefaultInstance() : vip_;
        } else {
          return vipBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public Builder setVip(proto_def.PeerMessage.Level value) {
        if (vipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vip_ = value;
          onChanged();
        } else {
          vipBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public Builder setVip(
          proto_def.PeerMessage.Level.Builder builderForValue) {
        if (vipBuilder_ == null) {
          vip_ = builderForValue.build();
          onChanged();
        } else {
          vipBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public Builder mergeVip(proto_def.PeerMessage.Level value) {
        if (vipBuilder_ == null) {
          if (vip_ != null) {
            vip_ =
              proto_def.PeerMessage.Level.newBuilder(vip_).mergeFrom(value).buildPartial();
          } else {
            vip_ = value;
          }
          onChanged();
        } else {
          vipBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public Builder clearVip() {
        if (vipBuilder_ == null) {
          vip_ = null;
          onChanged();
        } else {
          vip_ = null;
          vipBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public proto_def.PeerMessage.Level.Builder getVipBuilder() {
        
        onChanged();
        return getVipFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      public proto_def.PeerMessage.LevelOrBuilder getVipOrBuilder() {
        if (vipBuilder_ != null) {
          return vipBuilder_.getMessageOrBuilder();
        } else {
          return vip_ == null ?
              proto_def.PeerMessage.Level.getDefaultInstance() : vip_;
        }
      }
      /**
       * <code>.proto_def.Level vip = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto_def.PeerMessage.Level, proto_def.PeerMessage.Level.Builder, proto_def.PeerMessage.LevelOrBuilder> 
          getVipFieldBuilder() {
        if (vipBuilder_ == null) {
          vipBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto_def.PeerMessage.Level, proto_def.PeerMessage.Level.Builder, proto_def.PeerMessage.LevelOrBuilder>(
                  getVip(),
                  getParentForChildren(),
                  isClean());
          vip_ = null;
        }
        return vipBuilder_;
      }

      private proto_def.PeerMessage.Level noble_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto_def.PeerMessage.Level, proto_def.PeerMessage.Level.Builder, proto_def.PeerMessage.LevelOrBuilder> nobleBuilder_;
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public boolean hasNoble() {
        return nobleBuilder_ != null || noble_ != null;
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public proto_def.PeerMessage.Level getNoble() {
        if (nobleBuilder_ == null) {
          return noble_ == null ? proto_def.PeerMessage.Level.getDefaultInstance() : noble_;
        } else {
          return nobleBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public Builder setNoble(proto_def.PeerMessage.Level value) {
        if (nobleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          noble_ = value;
          onChanged();
        } else {
          nobleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public Builder setNoble(
          proto_def.PeerMessage.Level.Builder builderForValue) {
        if (nobleBuilder_ == null) {
          noble_ = builderForValue.build();
          onChanged();
        } else {
          nobleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public Builder mergeNoble(proto_def.PeerMessage.Level value) {
        if (nobleBuilder_ == null) {
          if (noble_ != null) {
            noble_ =
              proto_def.PeerMessage.Level.newBuilder(noble_).mergeFrom(value).buildPartial();
          } else {
            noble_ = value;
          }
          onChanged();
        } else {
          nobleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public Builder clearNoble() {
        if (nobleBuilder_ == null) {
          noble_ = null;
          onChanged();
        } else {
          noble_ = null;
          nobleBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public proto_def.PeerMessage.Level.Builder getNobleBuilder() {
        
        onChanged();
        return getNobleFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      public proto_def.PeerMessage.LevelOrBuilder getNobleOrBuilder() {
        if (nobleBuilder_ != null) {
          return nobleBuilder_.getMessageOrBuilder();
        } else {
          return noble_ == null ?
              proto_def.PeerMessage.Level.getDefaultInstance() : noble_;
        }
      }
      /**
       * <code>.proto_def.Level noble = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto_def.PeerMessage.Level, proto_def.PeerMessage.Level.Builder, proto_def.PeerMessage.LevelOrBuilder> 
          getNobleFieldBuilder() {
        if (nobleBuilder_ == null) {
          nobleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto_def.PeerMessage.Level, proto_def.PeerMessage.Level.Builder, proto_def.PeerMessage.LevelOrBuilder>(
                  getNoble(),
                  getParentForChildren(),
                  isClean());
          noble_ = null;
        }
        return nobleBuilder_;
      }

      private java.lang.Object gender_ = "";
      /**
       * <pre>
       *'F' for female, 'M' for male, 'U' for Unknown
       * </pre>
       *
       * <code>string gender = 6;</code>
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *'F' for female, 'M' for male, 'U' for Unknown
       * </pre>
       *
       * <code>string gender = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *'F' for female, 'M' for male, 'U' for Unknown
       * </pre>
       *
       * <code>string gender = 6;</code>
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *'F' for female, 'M' for male, 'U' for Unknown
       * </pre>
       *
       * <code>string gender = 6;</code>
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *'F' for female, 'M' for male, 'U' for Unknown
       * </pre>
       *
       * <code>string gender = 6;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_def.PeerUserInfo)
    }

    // @@protoc_insertion_point(class_scope:proto_def.PeerUserInfo)
    private static final proto_def.PeerMessage.PeerUserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_def.PeerMessage.PeerUserInfo();
    }

    public static proto_def.PeerMessage.PeerUserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PeerUserInfo>
        PARSER = new com.google.protobuf.AbstractParser<PeerUserInfo>() {
      @java.lang.Override
      public PeerUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeerUserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PeerUserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PeerUserInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto_def.PeerMessage.PeerUserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_def_Level_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_def_Level_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_def_PeerUserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_def_PeerUserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022peer_message.proto\022\tproto_def\"%\n\005Level" +
      "\022\r\n\005level\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\"\220\001\n\014PeerU" +
      "serInfo\022\016\n\006userId\030\001 \001(\t\022\020\n\010nickName\030\002 \001(" +
      "\t\022\016\n\006avatar\030\003 \001(\t\022\035\n\003vip\030\004 \001(\0132\020.proto_d" +
      "ef.Level\022\037\n\005noble\030\005 \001(\0132\020.proto_def.Leve" +
      "l\022\016\n\006gender\030\006 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_def_Level_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_def_Level_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_def_Level_descriptor,
        new java.lang.String[] { "Level", "Title", });
    internal_static_proto_def_PeerUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_def_PeerUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_def_PeerUserInfo_descriptor,
        new java.lang.String[] { "UserId", "NickName", "Avatar", "Vip", "Noble", "Gender", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
